[project]
name = "py-example"
version = "0.1.0"
description = "Provided as an example of LLM implementation on an API"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "transformers",
    "torch",
    "accelerate>=0.26.0",
    "fastapi[standard]",
    "pydantic",
    "uvicorn"
]